# Clippy configuration for the lints activated in Cargo.toml.
# https://doc.rust-lang.org/clippy/lint_configuration.html

# Configuration for unwrap_used and expect_used.
allow-unwrap-in-tests = true
allow-unwrap-in-consts = true
allow-expect-in-tests = true
allow-expect-in-consts = true
