volumes:
  pg_data:

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: database
