# Sorts `Cargo.toml` dependencies. All other `.toml` files are formatted with the default config.
#
# https://taplo.tamasfe.dev/configuration/file.html#configuration-file

include = ["Cargo.toml", "**/*.toml"]
exclude = [".direnv/*", "target/*", "result/*"]

[formatting]
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies",
  "workspace.dependencies",
  "build-dependencies",
  "dev-dependencies",
]
[rule.formatting]
reorder_keys = true
